import { Inter, Space_Grotesk, Caveat, Dancing_Script } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { AIChat } from "@/components/AIChat";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-handwriting",
  display: "swap",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-script",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "CodePro | Full Stack Developer & Software Engineer",
    template: "%s | CodePro",
  },
  description:
    "Building scalable SaaS platforms, AI-powered applications, backend APIs, and modern web experiences with React, Next.js, Node.js, Python, FastAPI, MongoDB, and AWS.",
  keywords: [
    "Full Stack Developer",
    "Software Engineer",
    "Freelance Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "Python Developer",
    "FastAPI Developer",
    "MongoDB Developer",
    "MERN Stack Developer",
    "SaaS Developer",
    "Backend Developer",
    "Frontend Developer",
    "AI Developer",
    "Web Developer India",
    "Remote Software Engineer",
    "API Development",
    "Portfolio",
    "CodePro",
    "Bhubaneswar",
    "Odisha",
    "India",
  ],
  authors: [{ name: "Dinakrushna Agasti", url: siteUrl }],
  creator: "Dinakrushna Agasti",
  publisher: "CodePro",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "CodePro | Full Stack Developer & Software Engineer",
    description:
      "Building modern SaaS applications, scalable backend APIs, AI-powered solutions, mobile apps, and high-performance web applications using React, Next.js, Node.js, Python, FastAPI, MongoDB, and AWS.",
    url: siteUrl,
    siteName: "CodePro",
    locale: "en_US",
    type: "website",
    // OG image is generated by src/app/opengraph-image.js
  },
  twitter: {
    card: "summary_large_image",
    title: "CodePro | Full Stack Developer & Software Engineer",
    description:
      "Building modern SaaS applications, scalable backend APIs, AI-powered solutions, mobile apps, and high-performance web applications.",
    // Twitter image is generated by src/app/twitter-image.js
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Favicon + apple icon are generated by src/app/icon.js and src/app/apple-icon.js
  alternates: {
    canonical: siteUrl,
  },
  verification: {
    // Add your Google Search Console verification code here
    // google: 'your-verification-code',
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#faf6ef",
  colorScheme: "light",
};

// JSON-LD Structured Data
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Dinakrushna Agasti",
  url: siteUrl,
  image: `${siteUrl}/logo.png`,
  jobTitle: "Full Stack Developer",
  description:
    "Full Stack Developer specializing in scalable SaaS platforms, backend engineering, AI-powered applications, and modern web development.",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Bhubaneswar",
    addressRegion: "Odisha",
    addressCountry: "IN",
  },
  knowsAbout: [
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "Python",
    "FastAPI",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Docker",
    "AWS",
    "REST API",
    "GraphQL",
    "JWT",
    "Authentication",
    "Microservices",
    "TypeScript",
    "Tailwind CSS",
    "React Native",
    "Expo",
    "AI Integration",
    "LLM",
  ],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "CodePro",
  url: siteUrl,
  description:
    "Professional portfolio showcasing full-stack software development, scalable backend engineering, SaaS products, AI solutions, and modern web applications.",
  author: {
    "@type": "Person",
    name: "Dinakrushna Agasti",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} ${caveat.variable} ${dancingScript.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </head>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          {children}
          <AIChat />
        </Providers>
      </body>
    </html>
  );
}
