// Hardcoded per the approved design brief until real project assets/CMS
// content are ready to replace the placeholders.
export const PROJECTS = [
  {
    id: 'dakota',
    featured: true,
    category: 'Website + Mobile App',
    name: 'Dakota',
    description: 'Premium invitation & booking platform',
    result: 'Increased user engagement by 100%',
    placeholderLabel: 'dakota-hero',
    placeholderRatio: '4/5',
    placeholderGallery: ['dakota-home', 'dakota-booking', 'dakota-checkout', 'dakota-mobile'],
  },
  {
    id: 'cvpilot',
    category: 'Website',
    name: 'CVPilot',
    description: 'AI-powered resume & career platform',
    result: 'Helped 10k+ users build better resumes',
    placeholderLabel: 'cvpilot-preview',
    placeholderGallery: ['cvpilot-editor', 'cvpilot-templates', 'cvpilot-ai-suggestions', 'cvpilot-export'],
  },
  {
    id: 'trall',
    category: 'Mobile App',
    name: 'Trall',
    description: 'Event & community app',
    result: '50k+ downloads',
    placeholderLabel: 'trall-preview',
    placeholderGallery: ['trall-feed', 'trall-event-page', 'trall-chat', 'trall-profile'],
  },
  {
    id: 'dakota-invite',
    category: 'Website',
    name: 'Dakota Invite',
    description: 'Event booking & guest management',
    result: 'Streamlined event booking process',
    placeholderLabel: 'dakota-invite-preview',
    placeholderGallery: ['invite-guest-list', 'invite-rsvp', 'invite-dashboard'],
  },
  {
    id: 'featureable',
    category: 'UI/UX',
    name: 'Featureable',
    description: 'Google reviews & reputation platform',
    result: '200% more customer reviews',
    placeholderLabel: 'featureable-preview',
    placeholderGallery: ['featureable-dashboard', 'featureable-widget', 'featureable-analytics'],
  },
];
